project:
  type: book
  output-dir: _book



book:
  title: "概率论讲义"
  author:
    - id: xz
      name: Your Name
      affiliations:
        - name: Your University
          department: Your Department
          city: Your City
          country: Your Country
          postal-code: 000000
      orcid: 0000-0000-0000-0001
      email: your.email@university.edu
      url: https://your-university.edu/your-profile
      #attributes:
        #corresponding: true
      bio: |
        Your bio text here. Briefly describe your research interests and background.
    #- name: John Doe
      #affiliations:
      #  - name: Anonymous University
      #bio: |
      #  John Doe is a researcher at Anonymous University.



  chapters:
    - index.qmd
    - chap1.qmd
    - chap2.qmd
    - ref.qmd

  site-url: https://your-site.example.com/
  downloads: [pdf]
  sharing: [twitter,facebook]
  page-navigation: true

  sidebar:
    ## collapse-level: 1
    search: true
    title: false
    logo: "images/openscapes_hex.png"
    logo-alt: "Openscapes hex logo (test)"
    pinned: true
    align: center
    style: "docked"
    tools:
      - icon: globe
        href: https://your-website.com
        text: "Your Website"
      - icon: github
        href: https://github.com/yourusername/yourrepo
        ## text: "Quarto website tutorial"
      - icon: twitter
        href: https://twitter.com/yourusername
        text: "My Twitter"
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Your Name</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>



bibliography: references.bib



format:
  html:
    lang: zh
    html-math-method: katex
    mainfont: Times New Roman
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: false
    css: styles.css
    crossref:
      chapters: true
      eq-prefix: ""
    number-depth: 2
    self-contained: false

  xbook-cn-pdf:
    pdf-engine: xelatex
    toc: false

# editor: visual
